language: python

python:
  - 3.6
#  - 2.7
#  - 3.5

before_install:
  - python --version
  - pip install -U pip
#  - pip install -U unittest
  - pip install codecov

#install:
#  - pip install ".[test]" . # install package + test dependencies

script: coverage run *.test.py # run tests

after_success:
  - codecov # submit coverage