name: CI

on: push

jobs:
  ci:
    name: CI for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Needed for codecov

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Lint and test
      run: make ci

    - name: Report test coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./.coverage.json
